language:
  - ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - ree
script:
  - bundle exec rspec
  - '! bundle show rubocop || bundle exec rubocop' # run rubocop only if it is bundled
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gifsicle jhead jpegoptim libjpeg-progs optipng pngcrush
  - npm install -g svgo
  - mkdir ~/bin

  - echo 'Installing advancecomp(advpng):'
  - ADVANCECOMP_VERSION=1.19
  - wget http://downloads.sourceforge.net/project/advancemame/advancecomp/$ADVANCECOMP_VERSION/advancecomp-$ADVANCECOMP_VERSION.tar.gz
  - tar -xzf advancecomp-$ADVANCECOMP_VERSION.tar.gz
  - (cd advancecomp-$ADVANCECOMP_VERSION && ./configure && make)
  - mv advancecomp-$ADVANCECOMP_VERSION/advpng ~/bin

  - echo 'Installing pngquant:'
  - git clone git://github.com/pornel/pngquant.git
  - (cd pngquant && git checkout $(git describe --tags --abbrev=0) && make)
  - mv pngquant/pngquant ~/bin

  - echo 'Installing pngout:'
  - PNGOUT_VERSION=20130221
  - wget http://static.jonof.id.au/dl/kenutils/pngout-$PNGOUT_VERSION-linux.tar.gz
  - tar -xzf pngout-$PNGOUT_VERSION-linux.tar.gz
  - mv pngout-$PNGOUT_VERSION-linux/x86_64/pngout ~/bin

  - echo 'Installing jpeg-recompress:'
  - JPEGARCHIVE_VERSION=2.0.1
  - wget https://github.com/danielgtaylor/jpeg-archive/releases/download/$JPEGARCHIVE_VERSION/jpeg-archive-$JPEGARCHIVE_VERSION-linux.tar.bz2
  - tar -xjf jpeg-archive-$JPEGARCHIVE_VERSION-linux.tar.bz2 jpeg-recompress
  - mv jpeg-recompress ~/bin
env:
  - PATH=~/bin:$PATH
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
