language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-18mode
  - jruby-19mode
  - ree
script:
  - test -n "$RUBOCOP" || bundle exec image_optim --info
  - test -n "$RUBOCOP" || bundle exec rspec
  - test -z "$RUBOCOP" || bundle exec rubocop
before_install:
  - mkdir ~/bin

  - echo 'Installing svgo:'
  - npm install -g svgo

  - echo 'Installing pngout:'
  - PNGOUT_VERSION=20130221
  - curl -L "http://static.jonof.id.au/dl/kenutils/pngout-$PNGOUT_VERSION-linux.tar.gz" | tar -xz
  - mv pngout-$PNGOUT_VERSION-linux/x86_64/pngout ~/bin
env:
  - PATH=~/bin:$PATH
matrix:
  fast_finish: true
  include:
    - env: RUBOCOP=true
      rvm: default
