language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - ree
script:
  - bundle exec image_optim --info
  - bundle exec rspec
  - '! bundle show rubocop || bundle exec rubocop' # run rubocop only if it is bundled
before_install:
  - mkdir ~/bin

  - echo 'Installing svgo:'
  - npm install -g svgo

  - echo 'Installing pngout:'
  - PNGOUT_VERSION=20130221
  - curl -L "http://static.jonof.id.au/dl/kenutils/pngout-$PNGOUT_VERSION-linux.tar.gz" | tar -xz
  - mv pngout-$PNGOUT_VERSION-linux/x86_64/pngout ~/bin
env:
  - PATH=~/bin:$PATH
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
