language:
  - objective-c
  - ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ree
script: bundle exec rspec
before_install:
  - wget -U curl http://imageoptim.com/ImageOptim.tbz2
  - tar -xjf ImageOptim.tbz2
  - brew install jhead
env:
  - PATH=ImageOptim.app/Contents/MacOS:$PATH
